apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres/postgres-stset.yml

  - todo-backend/todo-backend-clusterip.yml
  - todo-backend/todo-backend-deployment.yml
  - todo-backend/todo-backend-ingress.yml
  
  - todo/todo-pvc.yml
  - todo/todo-clusterip.yml
  - todo/todo-deployment.yml
  - todo/todo-ingress.yml

  - broadcaster/broadcaster-deployment.yml
  - broadcaster/broadcaster-clusterip.yml
images:
  - name: PROJECT/TODO_IMAGE
    newName: mashiahoz/todo
  - name: PROJECT/TODO_BACKEND_IMAGE
    newName: mashiahoz/todo-backend
  - name: PROJECT/POSTGRES_IMAGE
    newName: postgres:latest
  - name: PROJECT/BROADCASTER_IMAGE
    newName: mashiahoz/broadcaster
