FROM python:alpine

WORKDIR /usr/src/app

COPY ./requirements-pingpong.txt /usr/src/app

RUN pip install --no-cache-dir -r requirements-pingpong.txt

COPY ./pingpong.py /usr/src/app

EXPOSE 5000

CMD ["python3", "pingpong.py"]
