apiVersion: v1
kind: Service
metadata:
  namespace: logpong
  name: logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: logoutput 
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 5000 
