apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 

resources:
- postgres/postgres-stset.yml
- logoutput/logoutput-deployment.yml
- logoutput/logoutput-nodeport.yml
- logoutput/logoutput-ingress.yml
- logoutput/logoutput-configmap.yml
- pingpong/pingpong-deployment.yml
- pingpong/pingpong-clusterip.yml
images:
- name: PROJECT/LOGOUTPUT_IMAGE
  newName: mashiahoz/logoutput
  newTag: f1fbcaf482e8625e4198b0ae74665679389c58df
- name: PROJECT/PINGPONG_IMAGE
  newName: mashiahoz/pingpong
  newTag: f1fbcaf482e8625e4198b0ae74665679389c58df
- name: PROJECT/POSTGRES_IMAGE
  newName: postgres:latest
