apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 

resources:
- postgres/postgres-stset.yml
- logoutput/logoutput-deployment.yml
- logoutput/logoutput-nodeport.yml
- logoutput/logoutput-ingress.yml
- pingpong/pingpong-deployment.yml
- pingpong/pingpong-clusterip.yml
images:
- name: PROJECT/LOGOUTPUT_IMAGE
  newName: mashiahoz/logoutput
  newTag: 4c748ea6a4160d5088c4276b129591b334f03483
- name: PROJECT/PINGPONG_IMAGE
  newName: mashiahoz/pingpong
  newTag: 4c748ea6a4160d5088c4276b129591b334f03483
- name: PROJECT/POSTGRES_IMAGE
  newName: postgres:latest
