apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 

resources:
- postgres/postgres-stset.yml
- logoutput/logoutput-deployment.yml
- logoutput/logoutput-nodeport.yml
- logoutput/logoutput-ingress.yml
- logoutput/logoutput-configmap.yml
- pingpong/pingpong-deployment.yml
- pingpong/pingpong-clusterip.yml
images:
- name: PROJECT/LOGOUTPUT_IMAGE
  newName: mashiahoz/logoutput
  newTag: 948d5d0527ed25f9d43cc6bcb1fc303f7564b805
- name: PROJECT/PINGPONG_IMAGE
  newName: mashiahoz/pingpong
  newTag: 948d5d0527ed25f9d43cc6bcb1fc303f7564b805
- name: PROJECT/POSTGRES_IMAGE
  newName: postgres:latest
