apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres/postgres-stset.yml
- postgres/postgrespass-secret.yml
 
- logoutput/logoutput-deployment.yml
- logoutput/logoutput-nodeport.yml
- logoutput/logoutput-ingress.yml

- pingpong/pingpong-deployment.yml
- pingpong/pingpong-clusterip.yml
images:
- name: PROJECT/LOGOUTPUT_IMAGE
  newName: mashiahoz/logoutput
- name: PROJECT/PINGPONG_IMAGE
  newName: mashiahoz/pingpong
- name: PROJECT/POSTGRES_IMAGE
  newName: postgres:latest
