apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 

resources:
- postgres/postgres-stset.yml
- logoutput/logoutput-deployment.yml
- logoutput/logoutput-nodeport.yml
- logoutput/logoutput-ingress.yml
- logoutput/logoutput-configmap.yml
- pingpong/pingpong-deployment.yml
- pingpong/pingpong-clusterip.yml
images:
- name: PROJECT/LOGOUTPUT_IMAGE
  newName: mashiahoz/logoutput
  newTag: a4cc3dbc6d88c6fa73ad2d823a2819cf778f07b8
- name: PROJECT/PINGPONG_IMAGE
  newName: mashiahoz/pingpong
  newTag: a4cc3dbc6d88c6fa73ad2d823a2819cf778f07b8
- name: PROJECT/POSTGRES_IMAGE
  newName: postgres:latest
