apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres/postgres-stset.yml
- todo-backend/todo-backend-clusterip.yml
- todo-backend/todo-backend-deployment.yml
- todo/todo-pvc.yml
- todo/todo-clusterip.yml
- todo/todo-deployment.yml
- reverseproxy/reverseproxy-deployment.yml
- reverseproxy/reverseproxy-nodeport.yml
- reverseproxy/reverseproxy-ingress.yml
