apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
data:
    DB_PASSWORD: ENC[AES256_GCM,data:wmijiAy11eFLFDb4/xhVDg==,iv:lcJ6c6kaizPrsb6PHa/Dy1UXHuxwWdj1WEFVyFtMJO8=,tag:ai1Uq3B0ujZh5EYH0cfigg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10j6qkpgfkn9th64el5sau0vaz03lm8eq6r6x2dwvh3mkz95k4dqqfsdlsc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTkt5MFA3RkVkVk1ySzl2
            TTRVRG51eVJqM1pXYkFCelRSd2FPRlpiM1ZvCmpVSGZsQTBNVktZUzZuQ1pFRklu
            YkZjMVZYa3JIUUJKMEd4TE9Fa1NlcE0KLS0tIHlwanc5ZzVSanNkUjFyeHpJRUc2
            SDlYdHQ1UElpL1hXZGpZWFIrZDh4WVEK0EUJLACOr0+DNyChhpkVhsTXjEWVaPRr
            XqA9aeX8RlSc0F/OSXaYdk3UdZMgZJx5aYAzE0kgvbTtsmx4JXBltA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T13:52:24Z"
    mac: ENC[AES256_GCM,data:ZkpIlmc2cbTItiApxKlOYhNSiRPPnXNm/guf9U9Y4ng+8gWTacIZdqviScF+WR/lQaMoWCCWz+8bCM2W0pNIF6Sy9+hg1iudfeyCnC8qbTzVve5rT5bdvf6A4KTfpOO9rNnssEPb1pSVDvIscb2V4hUwY6lWpDl+AufMkKyfFMQ=,iv:uZpwSNoDoNN8orc4JF4GxR5AJUPHb3NGcxo8mb+Fil4=,tag:iZKEud46o1MvU3IZUiOgfg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
