apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: broadcaster-svc
spec:
  type: ClusterIP
  selector:
    app: broadcaster
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 5002
