resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

namePrefix: staging-

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 64f16cf2fe4898638d3343c27085ae47ce70bd34
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 64f16cf2fe4898638d3343c27085ae47ce70bd34
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 64f16cf2fe4898638d3343c27085ae47ce70bd34
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
