resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 9b62cf885224ecb70e96ac1286a2ef67f61a394a
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 9b62cf885224ecb70e96ac1286a2ef67f61a394a
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 9b62cf885224ecb70e96ac1286a2ef67f61a394a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
