resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: d3afef462d78f0d2b0b46bd3d4605fcbd117eede
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: d3afef462d78f0d2b0b46bd3d4605fcbd117eede
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: d3afef462d78f0d2b0b46bd3d4605fcbd117eede
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
