resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 0a10017721cc30749e6e8d8b8a1ccd30a1d59aab
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 0a10017721cc30749e6e8d8b8a1ccd30a1d59aab
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 0a10017721cc30749e6e8d8b8a1ccd30a1d59aab
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
