resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 184f7bef1b9a231f43ad380dae4c3556b60b5b70
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 184f7bef1b9a231f43ad380dae4c3556b60b5b70
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 184f7bef1b9a231f43ad380dae4c3556b60b5b70
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
