resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: ae00c2bb3d7376301358d833223fe677af2d09ff
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: ae00c2bb3d7376301358d833223fe677af2d09ff
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: ae00c2bb3d7376301358d833223fe677af2d09ff
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
