resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

namePrefix: staging-

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 6d855e84447ae877c084cb7ba87cbba4c75f04b9
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 6d855e84447ae877c084cb7ba87cbba4c75f04b9
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 6d855e84447ae877c084cb7ba87cbba4c75f04b9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
