resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: efd69dbde11c503c935928a0b732cb8a726f02de
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: efd69dbde11c503c935928a0b732cb8a726f02de
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: efd69dbde11c503c935928a0b732cb8a726f02de
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
