resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 9dd42005a3a58621deb813245701632edbcbcfd1
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 9dd42005a3a58621deb813245701632edbcbcfd1
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 9dd42005a3a58621deb813245701632edbcbcfd1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
