resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: dce3a4715482f066409de19908c7d2fe0c033c4a
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: dce3a4715482f066409de19908c7d2fe0c033c4a
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: dce3a4715482f066409de19908c7d2fe0c033c4a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
