resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

namePrefix: staging-

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: c6681a1d1bdd3b4dd7f7a362534779865d7c7a9b
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: c6681a1d1bdd3b4dd7f7a362534779865d7c7a9b
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: c6681a1d1bdd3b4dd7f7a362534779865d7c7a9b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
