resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: ac0448a076fa7f2e01ac48a2b9ec76afc9b2fbe8
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: ac0448a076fa7f2e01ac48a2b9ec76afc9b2fbe8
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: ac0448a076fa7f2e01ac48a2b9ec76afc9b2fbe8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
