resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster:justlog
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 1c4589ee29164cfc7225a0f056e62f5f8df4a03f
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 1c4589ee29164cfc7225a0f056e62f5f8df4a03f
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 1c4589ee29164cfc7225a0f056e62f5f8df4a03f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
