# permissions for end users to view dummysites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-viewer-role
rules:
- apiGroups:
  - part5.dwk.part5.dwk
  resources:
  - dummysites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - part5.dwk.part5.dwk
  resources:
  - dummysites/status
  verbs:
  - get
