apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: logpong
spec:
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: mashiahoz/pingpong
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: DB_PASSWORD
