resources:
- ./../../base
- broadcaster/broadcaster-deployment.yml
- db-backup/postgresbackup-cronjob.yml

images:
- name: PROJECT/BACKUP_IMAGE
  newName: mashiahoz/postgresbackup
- name: PROJECT/BROADCASTER_IMAGE
  newName: mashiahoz/broadcaster
  newTag: 422d0be7f4f373e01e5f4799c4c2b135f041ae95
- name: PROJECT/REVERSEPROXY_IMAGE
  newName: mashiahoz/reverseproxy
  newTag: 422d0be7f4f373e01e5f4799c4c2b135f041ae95
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: mashiahoz/todo-backend
  newTag: 422d0be7f4f373e01e5f4799c4c2b135f041ae95
- name: PROJECT/TODO_IMAGE
  newName: mashiahoz/todo
  newTag: 422d0be7f4f373e01e5f4799c4c2b135f041ae95
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
