apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: todo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
