apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 1m
    successCondition: result[0] < 50.0
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1735-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="todo"}[1m])) * 100
