name: Build and publish application

on:
  push:

env:
  SOPS_AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
  PARTEXERCISE_PATH: part4/exercise07

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sops
        run: |
          set -euo pipefail
          wget https://github.com/getsops/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb
          echo ' 535bce529e2df7368ffba3fed2b427b9f964318fa28959d913924a70ba01c086  sops_3.8.1_amd64.deb' > sops_3.8.1_amd64.deb.sig
          sha256sum -c sops_3.8.1_amd64.deb.sig
          sudo dpkg -i sops_3.8.1_amd64.deb

      - name: Import age private key
        run: |
          echo "$SOPS_AGE_PRIVATE_KEY" > /tmp/age.key
          export SOPS_AGE_KEY_FILE=/tmp/age.key
          sops -d $PARTEXERCISE_PATH/postgres/postgrespass-secret.enc.yml > $PARTEXERCISE_PATH/postgres/postgrespass-secret.yml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          cd $PARTEXERCISE_PATH
          docker build --tag "mashiahoz/logoutput:$GITHUB_SHA" ./logoutput
          docker push "mashiahoz/logoutput:$GITHUB_SHA"

          docker build --tag "mashiahoz/pingpong:$GITHUB_SHA" ./pingpong
          docker push "mashiahoz/pingpong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd $PARTEXERCISE_PATH
          kustomize edit set image PROJECT/LOGOUTPUT_IMAGE=mashiahoz/logoutput:$GITHUB_SHA
          kustomize edit set image PROJECT/PINGPONG_IMAGE=mashiahoz/pingpong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yml'
          message: New version released ${{ github.sha }}

      - name: Clean up decrypted secrets
        run: rm $PARTEXERCISE_PATH/postgres/postgrespass-secret.yml
